### ISSUE TITLE
ICAP Java Example for encrypted communication

### ISSUE THREAD

**Issue by slissek** [Baekalfen/ICAP-avscan#16]
I was just wondering what must be changed in the example code to switch to an encrypted communication between the ICAP client and the server.

Serverside has configured the port 11344 to accept encrypted messages. 

What else has to be changed beside the port to establish the connection?

I will be thankful for any hint.

**Comment by Baekalfen** [comment]
It depends on the encryption you want to use. If you can setup an SSL connection, it would be fairly easy to just change the lines that initialize the stream. In the Java version, it would be around this line:

https://github.com/Baekalfen/ICAP-avscan/blob/f87ac6c6509b30dff6a9e1eb06f34ab590f9985c/Java/ICAP/src/icap_samplecode/ICAP.java#L103

But you would want to get the streams from the SSL connection, instead of the raw socket.

**Comment by slissek** [comment]
For all the others who may be interested to what have to be changed, here is the list of todos:

- replace the Socket with a SSLSocket
- use SSLSocketFactory.getDefault().createSocket() to instantiate it
- change port to SSL version
- create and reference a trust store for the service runtime
